[package]
name = "bento_derive"
version = "0.1.0"
authors = ["Federico Morrone <contact@morrone.dev>"]
edition = "2021"

[dependencies]
bento = { version = "0.1.0", path = "../bento"} 

[lib]
proc-macro = true